name: deploy to vps
'on':
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout dist repo
      #   uses: actions/checkout@v4

      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
          
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build
      #     ls -lh

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: whoami

