name: deploy to vps
'on':
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dist repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Build
        run: |
          npm install
          npm run build
          ls -lh
      
      - name: Upload dist to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: '${{ secrets.SSH_PRIVATE_KEY }}'
          SOURCE: dist/
          REMOTE_HOST: '${{ secrets.REMOTE_HOST }}'
          REMOTE_USER: '${{ secrets.REMOTE_USER }}'
          TARGET: '${{ secrets.TARGET }}'
